package com.skhoron.vault.ui

import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.skhoron.vault.R
import com.skhoron.vault.generator.GeneratedPassword
import com.skhoron.vault.generator.GeneratorOptions
import com.skhoron.vault.generator.PasswordGenerator
import com.skhoron.vault.ui.theme.SkhoronAccent
import com.skhoron.vault.ui.theme.SkhoronTextDim

/**
 * suggestedLabel — передаётся извне (из AutofillService: домен страницы или имя
 * пакета приложения). Юзер может отредактировать перед сохранением.
 */
@Composable
fun GeneratorScreen(
    suggestedLabel: String? = null,
    onSave: (label: String, username: String?, password: String) -> Unit,
    onCancel: () -> Unit,
    modifier: Modifier = Modifier
) {
    val generator = remember { PasswordGenerator() }
    var options by remember { mutableStateOf(GeneratorOptions()) }
    var generated by remember { mutableStateOf(generator.generate(options)) }
    var label by remember { mutableStateOf(suggestedLabel ?: "") }
    var username by remember { mutableStateOf("") }

    fun regenerate() {
        generated = generator.generate(options)
    }

    Column(
        modifier = modifier.fillMaxSize().padding(24.dp),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Text(stringResource(R.string.generate_password), fontSize = 22.sp, fontWeight = androidx.compose.ui.text.font.FontWeight.SemiBold)
        Spacer(Modifier.height(20.dp))

        PasswordDisplay(generated)

        Spacer(Modifier.height(16.dp))
        Text(
            text = stringResource(R.string.entropy_label, generated.entropyBits.toInt()),
            color = SkhoronAccent,
            fontSize = 14.sp
        )
        Text(generated.comparisonLabel(), color = SkhoronTextDim, fontSize = 12.sp)

        Spacer(Modifier.height(24.dp))
        Text(stringResource(R.string.password_length), fontSize = 13.sp, color = SkhoronTextDim)
        Slider(
            value = options.length.toFloat(),
            onValueChange = {
                options = options.copy(length = it.toInt())
                regenerate()
            },
            valueRange = 8f..128f
        )
        Text("${options.length} символов", fontSize = 12.sp, color = SkhoronTextDim)

        Spacer(Modifier.height(8.dp))
        Button(onClick = { regenerate() }, modifier = Modifier.fillMaxWidth()) {
            Text("Сгенерировать заново")
        }

        Spacer(Modifier.height(24.dp))
        Divider()
        Spacer(Modifier.height(16.dp))

        OutlinedTextField(
            value = label,
            onValueChange = { label = it },
            label = { Text(stringResource(R.string.label_hint)) },
            singleLine = true,
            modifier = Modifier.fillMaxWidth()
        )
        Spacer(Modifier.height(12.dp))
        OutlinedTextField(
            value = username,
            onValueChange = { username = it },
            label = { Text(stringResource(R.string.username_hint)) },
            singleLine = true,
            modifier = Modifier.fillMaxWidth()
        )

        Spacer(Modifier.height(20.dp))
        Row(modifier = Modifier.fillMaxWidth()) {
            OutlinedButton(onClick = onCancel, modifier = Modifier.weight(1f)) {
                Text(stringResource(R.string.cancel))
            }
            Spacer(Modifier.width(12.dp))
            Button(
                onClick = { onSave(label.ifBlank { suggestedLabel ?: "Без названия" }, username.ifBlank { null }, generated.value) },
                enabled = label.isNotBlank() || suggestedLabel != null,
                modifier = Modifier.weight(1f)
            ) {
                Text(stringResource(R.string.save))
            }
        }
    }
}

@Composable
private fun PasswordDisplay(generated: GeneratedPassword) {
    Card(modifier = Modifier.fillMaxWidth()) {
        Text(
            text = generated.value,
            fontFamily = FontFamily.Monospace,
            fontSize = 13.sp,
            modifier = Modifier.padding(16.dp)
        )
    }
}